---
title: "Introduction"
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE,comment = "#>")
```

This vigentte will get you started extracting actively-flowing river networks from remotely sensed imagery!

# Preprocessing
`SARNr` assumes you have the following data prepared:

- Multi-band remote sensing image with at least the following bands: green, red, and nir. We developed `SARNr` around Planet imagery and so these bands are the bare minimum, though other sensors can be used to calculate other spectral indices for river classification.
- DEM river network of equivalent (or better) resolution to your remotely sensed image(s). This resolution requirement is important!

One can also generate their DEM river network in a GIS: to my knowledge there is no easy way to do this in R currently. This needs to only be done once. The general workflow is the following (there are tons of tutorials online for doing this in ArcGIS, QGIS, GRASS, etc.)

- Fill sinks
- Generate flow directions
- Generate flow accumulation grid
- Set channelization threshold and create binary river network
- Convert this raster river network to vector

# Workflow
Below is an example code for generating an actively flowing drainage network given a DEM river network and an RS river network. The example uses a Planet 3m image from 10/09/2020 in the Nepalese Himalaya.

Load in the required packages
```R
library(SARNr)
library(sf) #for vector processing
library(terra) #for raster processing
```

Load in the necessary data
```R
#load in data
rivnet_dem <- st_read('data/DEM_rivnet_33333_20201009_045732_0f17.shp') #DEM river networks
dem_domain <- rast('data/dem_fin_20201009_045732_0f17.tif') #dem downscaled to 3m
image <- rast('data/PSScene4Band-20201009_045732_0f17.tif') #3m PlanetScope image
```

Classify water within your image. You can do this using bespoke methods or one of the two functions included here (see below). Here we use NDWI-NDVI to force as much spectral contrast between land and water as possible following  https://doi.org/10.3390/s18082580.

```R
#Rosgen's Unimodal thresholding approach applied to the spectral index (NDWI-NDVI)
rivnet_rs_rast <- sarn_classifyWater_unimodal(img = image,
                                     dem = dem_domain,
                                     maxElev = 4000) #water is ignored above this elevation (to remove snow/ice/glaciers)

#Otsu's bimodal thresholding approach applied to the spectral indec (NDWI-NDVI)
rivnet_rs_rast <- sarn_classifyWater_bimodal(img = image,
                                     dem = dem_domain,
                                     maxElev = 4000) #water is ignored above this elevation (to remove snow/ice/glaciers)
```

Run the algorithm
```R
#run SARNr
data <- sarn_data(dem_network = rivnet_dem,
                  riverMask = rivnet_rs_rast,
                  dem = dem_domain) #create SARN object

joinedNetwork <- sarn_joinNetworks(data = data, 
                                   bufferSize=5) #join DEM and RS networks

trimmedNetwork <- sarn_trimNetworks(networks = joinedNetwork,
                                    printOutput = 'Yes') #trim combined DEM/RS network

fin <- sarn_hydrography(trimmedNetwork = trimmedNetwork$trimmedNetwork, 
                        dem = data$dem,
                        riverMask = data$riverMask, 
                        lengthThresh = 50,
                        printOutput = 'Yes') #build hydrography

#save river network to shp
st_write(fin, 'debug/hydrography.shp', delete_dsn = TRUE)
```
